packages:
  - packages/*

catalogs:
  prisma:
    prisma: latest

syncInjectedDepsAfterScripts:
  - build

injectWorkspacePackages: true

onlyBuiltDependencies:
  - sqlite3
  - prisma
  - "@prisma/client"
  - ts-node
  - typescript
