packages:
  - packages/config
  - packages/database
  - packages/env
  - packages/server
  - packages/web

catalogs:
  prisma:
    prisma: latest

syncInjectedDepsAfterScripts:
- build
injectWorkspacePackages: true
